[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake",
    "ninja",
    "packaging",
    "pybind11>=2.10.1",
    "PyYAML",
    "requests",
]
build-backend = "setuptools.build_meta"
