// Copyright 2026 The IREE Authors
//
// Licensed under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

#ifndef IREE_COMPILER_CODEGEN_DIALECT_TEMPLATE_IR_TEMPLATEDIALECT_H_
#define IREE_COMPILER_CODEGEN_DIALECT_TEMPLATE_IR_TEMPLATEDIALECT_H_

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"

namespace mlir::iree_compiler::IREE::Template {

class TemplateDialect : public Dialect {
public:
  explicit TemplateDialect(MLIRContext *context);
  static StringRef getDialectNamespace() { return "template"; }

  // Type parsing and printing - implementations generated by tablegen.
  Type parseType(DialectAsmParser &parser) const override;
  void printType(Type type, DialectAsmPrinter &p) const override;

private:
  void registerOperations();
  void registerAttributes();
  void registerTypes();
};

} // namespace mlir::iree_compiler::IREE::Template

#endif // IREE_COMPILER_CODEGEN_DIALECT_TEMPLATE_IR_TEMPLATEDIALECT_H_
