# Builds the TFLite Java Bindings Android Library using the gradle-android
# Docker image.
name: Build TFLite Android Library

on:
  workflow_dispatch:

jobs:
  build_android_with_docker:
    runs-on: ubuntu-20.04
    env:
      ANDROID_CONTAINER: "gcr.io/iree-oss/gradle-android@sha256:da1285940a75c5fcef96bc4f21c9099ba1beb06a65dde2680aabb3dcce6729ad"
    steps:
      - uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0
        with:
          submodules: true
      - name: Execute Android Build
        run: |
          docker run --rm \
          -w=/work \
          -v $PWD:/work \
          "${ANDROID_CONTAINER}" \
          bash -c build_tools/gradle/build_tflite_android_library.sh
      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # v2
        with:
          path: ./runtime/bindings/tflite/java/build/outputs/aar/*.aar
          retention-days: 1
